// 自动生成的系统错误码定义源文件
// extract_errno_info.py从系统errno.h及相关头文件提取

#include "system_errors.h"

namespace wf::utils {

// 系统错误静态对象定义
namespace system_errors {
error_info system_UNKNOWN = "Unknown system error";
error_info system_EPERM = "Operation not permitted";
error_info system_ENOENT = "No such file or directory";
error_info system_ESRCH = "No such process";
error_info system_EINTR = "Interrupted system call";
error_info system_EIO = "Input/output error";
error_info system_ENXIO = "No such device or address";
error_info system_E2BIG = "Argument list too long";
error_info system_ENOEXEC = "Exec format error";
error_info system_EBADF = "Bad file descriptor";
error_info system_ECHILD = "No child processes";
error_info system_EAGAIN = "Resource temporarily unavailable";
error_info system_ENOMEM = "Cannot allocate memory";
error_info system_EACCES = "Permission denied";
error_info system_EFAULT = "Bad address";
error_info system_ENOTBLK = "Block device required";
error_info system_EBUSY = "Device or resource busy";
error_info system_EEXIST = "File exists";
error_info system_EXDEV = "Invalid cross-device link";
error_info system_ENODEV = "No such device";
error_info system_ENOTDIR = "Not a directory";
error_info system_EISDIR = "Is a directory";
error_info system_EINVAL = "Invalid argument";
error_info system_ENFILE = "Too many open files in system";
error_info system_EMFILE = "Too many open files";
error_info system_ENOTTY = "Inappropriate ioctl for device";
error_info system_ETXTBSY = "Text file busy";
error_info system_EFBIG = "File too large";
error_info system_ENOSPC = "No space left on device";
error_info system_ESPIPE = "Illegal seek";
error_info system_EROFS = "Read-only file system";
error_info system_EMLINK = "Too many links";
error_info system_EPIPE = "Broken pipe";
error_info system_EDOM = "Numerical argument out of domain";
error_info system_ERANGE = "Numerical result out of range";
error_info system_EDEADLK = "Resource deadlock avoided";
error_info system_ENAMETOOLONG = "File name too long";
error_info system_ENOLCK = "No locks available";
error_info system_ENOSYS = "Function not implemented";
error_info system_ENOTEMPTY = "Directory not empty";
error_info system_ELOOP = "Too many levels of symbolic links";
error_info system_ENOMSG = "No message of desired type";
error_info system_EIDRM = "Identifier removed";
error_info system_ECHRNG = "Channel number out of range";
error_info system_EL2NSYNC = "Level 2 not synchronized";
error_info system_EL3HLT = "Level 3 halted";
error_info system_EL3RST = "Level 3 reset";
error_info system_ELNRNG = "Link number out of range";
error_info system_EUNATCH = "Protocol driver not attached";
error_info system_ENOCSI = "No CSI structure available";
error_info system_EL2HLT = "Level 2 halted";
error_info system_EBADE = "Invalid exchange";
error_info system_EBADR = "Invalid request descriptor";
error_info system_EXFULL = "Exchange full";
error_info system_ENOANO = "No anode";
error_info system_EBADRQC = "Invalid request code";
error_info system_EBADSLT = "Invalid slot";
error_info system_EBFONT = "Bad font file format";
error_info system_ENOSTR = "Device not a stream";
error_info system_ENODATA = "No data available";
error_info system_ETIME = "Timer expired";
error_info system_ENOSR = "Out of streams resources";
error_info system_ENONET = "Machine is not on the network";
error_info system_ENOPKG = "Package not installed";
error_info system_EREMOTE = "Object is remote";
error_info system_ENOLINK = "Link has been severed";
error_info system_EADV = "Advertise error";
error_info system_ESRMNT = "Srmount error";
error_info system_ECOMM = "Communication error on send";
error_info system_EPROTO = "Protocol error";
error_info system_EMULTIHOP = "Multihop attempted";
error_info system_EDOTDOT = "RFS specific error";
error_info system_EBADMSG = "Bad message";
error_info system_EOVERFLOW = "Value too large for defined data type";
error_info system_ENOTUNIQ = "Name not unique on network";
error_info system_EBADFD = "File descriptor in bad state";
error_info system_EREMCHG = "Remote address changed";
error_info system_ELIBACC = "Can not access a needed shared library";
error_info system_ELIBBAD = "Accessing a corrupted shared library";
error_info system_ELIBSCN = ".lib section in a.out corrupted";
error_info system_ELIBMAX = "Attempting to link in too many shared libraries";
error_info system_ELIBEXEC = "Cannot exec a shared library directly";
error_info system_EILSEQ = "Invalid or incomplete multibyte or wide character";
error_info system_ERESTART = "Interrupted system call should be restarted";
error_info system_ESTRPIPE = "Streams pipe error";
error_info system_EUSERS = "Too many users";
error_info system_ENOTSOCK = "Socket operation on non-socket";
error_info system_EDESTADDRREQ = "Destination address required";
error_info system_EMSGSIZE = "Message too long";
error_info system_EPROTOTYPE = "Protocol wrong type for socket";
error_info system_ENOPROTOOPT = "Protocol not available";
error_info system_EPROTONOSUPPORT = "Protocol not supported";
error_info system_ESOCKTNOSUPPORT = "Socket type not supported";
error_info system_EOPNOTSUPP = "Operation not supported";
error_info system_EPFNOSUPPORT = "Protocol family not supported";
error_info system_EAFNOSUPPORT = "Address family not supported by protocol";
error_info system_EADDRINUSE = "Address already in use";
error_info system_EADDRNOTAVAIL = "Cannot assign requested address";
error_info system_ENETDOWN = "Network is down";
error_info system_ENETUNREACH = "Network is unreachable";
error_info system_ENETRESET = "Network dropped connection on reset";
error_info system_ECONNABORTED = "Software caused connection abort";
error_info system_ECONNRESET = "Connection reset by peer";
error_info system_ENOBUFS = "No buffer space available";
error_info system_EISCONN = "Transport endpoint is already connected";
error_info system_ENOTCONN = "Transport endpoint is not connected";
error_info system_ESHUTDOWN = "Cannot send after transport endpoint shutdown";
error_info system_ETOOMANYREFS = "Too many references: cannot splice";
error_info system_ETIMEDOUT = "Connection timed out";
error_info system_ECONNREFUSED = "Connection refused";
error_info system_EHOSTDOWN = "Host is down";
error_info system_EHOSTUNREACH = "No route to host";
error_info system_EALREADY = "Operation already in progress";
error_info system_EINPROGRESS = "Operation now in progress";
error_info system_ESTALE = "Stale file handle";
error_info system_EUCLEAN = "Structure needs cleaning";
error_info system_ENOTNAM = "Not a XENIX named type file";
error_info system_ENAVAIL = "No XENIX semaphores available";
error_info system_EISNAM = "Is a named type file";
error_info system_EREMOTEIO = "Remote I/O error";
error_info system_EDQUOT = "Disk quota exceeded";
error_info system_ENOMEDIUM = "No medium found";
error_info system_EMEDIUMTYPE = "Wrong medium type";
error_info system_ECANCELED = "Operation canceled";
error_info system_ENOKEY = "Required key not available";
error_info system_EKEYEXPIRED = "Key has expired";
error_info system_EKEYREVOKED = "Key has been revoked";
error_info system_EKEYREJECTED = "Key was rejected by service";
error_info system_EOWNERDEAD = "Owner died";
error_info system_ENOTRECOVERABLE = "State not recoverable";
error_info system_ERFKILL = "Operation not possible due to RF-kill";
error_info system_EHWPOISON = "Memory page has hardware error";
}

// 根据错误码值获取对应的错误信息对象
error_info system_error(int errno_value) {
    switch (errno_value) {
      case 0: return nullptr;
      case 1: return system_errors::system_EPERM;
      case 2: return system_errors::system_ENOENT;
      case 3: return system_errors::system_ESRCH;
      case 4: return system_errors::system_EINTR;
      case 5: return system_errors::system_EIO;
      case 6: return system_errors::system_ENXIO;
      case 7: return system_errors::system_E2BIG;
      case 8: return system_errors::system_ENOEXEC;
      case 9: return system_errors::system_EBADF;
      case 10: return system_errors::system_ECHILD;
      case 11: return system_errors::system_EAGAIN;
      case 12: return system_errors::system_ENOMEM;
      case 13: return system_errors::system_EACCES;
      case 14: return system_errors::system_EFAULT;
      case 15: return system_errors::system_ENOTBLK;
      case 16: return system_errors::system_EBUSY;
      case 17: return system_errors::system_EEXIST;
      case 18: return system_errors::system_EXDEV;
      case 19: return system_errors::system_ENODEV;
      case 20: return system_errors::system_ENOTDIR;
      case 21: return system_errors::system_EISDIR;
      case 22: return system_errors::system_EINVAL;
      case 23: return system_errors::system_ENFILE;
      case 24: return system_errors::system_EMFILE;
      case 25: return system_errors::system_ENOTTY;
      case 26: return system_errors::system_ETXTBSY;
      case 27: return system_errors::system_EFBIG;
      case 28: return system_errors::system_ENOSPC;
      case 29: return system_errors::system_ESPIPE;
      case 30: return system_errors::system_EROFS;
      case 31: return system_errors::system_EMLINK;
      case 32: return system_errors::system_EPIPE;
      case 33: return system_errors::system_EDOM;
      case 34: return system_errors::system_ERANGE;
      case 35: return system_errors::system_EDEADLK;
      case 36: return system_errors::system_ENAMETOOLONG;
      case 37: return system_errors::system_ENOLCK;
      case 38: return system_errors::system_ENOSYS;
      case 39: return system_errors::system_ENOTEMPTY;
      case 40: return system_errors::system_ELOOP;
      case 42: return system_errors::system_ENOMSG;
      case 43: return system_errors::system_EIDRM;
      case 44: return system_errors::system_ECHRNG;
      case 45: return system_errors::system_EL2NSYNC;
      case 46: return system_errors::system_EL3HLT;
      case 47: return system_errors::system_EL3RST;
      case 48: return system_errors::system_ELNRNG;
      case 49: return system_errors::system_EUNATCH;
      case 50: return system_errors::system_ENOCSI;
      case 51: return system_errors::system_EL2HLT;
      case 52: return system_errors::system_EBADE;
      case 53: return system_errors::system_EBADR;
      case 54: return system_errors::system_EXFULL;
      case 55: return system_errors::system_ENOANO;
      case 56: return system_errors::system_EBADRQC;
      case 57: return system_errors::system_EBADSLT;
      case 59: return system_errors::system_EBFONT;
      case 60: return system_errors::system_ENOSTR;
      case 61: return system_errors::system_ENODATA;
      case 62: return system_errors::system_ETIME;
      case 63: return system_errors::system_ENOSR;
      case 64: return system_errors::system_ENONET;
      case 65: return system_errors::system_ENOPKG;
      case 66: return system_errors::system_EREMOTE;
      case 67: return system_errors::system_ENOLINK;
      case 68: return system_errors::system_EADV;
      case 69: return system_errors::system_ESRMNT;
      case 70: return system_errors::system_ECOMM;
      case 71: return system_errors::system_EPROTO;
      case 72: return system_errors::system_EMULTIHOP;
      case 73: return system_errors::system_EDOTDOT;
      case 74: return system_errors::system_EBADMSG;
      case 75: return system_errors::system_EOVERFLOW;
      case 76: return system_errors::system_ENOTUNIQ;
      case 77: return system_errors::system_EBADFD;
      case 78: return system_errors::system_EREMCHG;
      case 79: return system_errors::system_ELIBACC;
      case 80: return system_errors::system_ELIBBAD;
      case 81: return system_errors::system_ELIBSCN;
      case 82: return system_errors::system_ELIBMAX;
      case 83: return system_errors::system_ELIBEXEC;
      case 84: return system_errors::system_EILSEQ;
      case 85: return system_errors::system_ERESTART;
      case 86: return system_errors::system_ESTRPIPE;
      case 87: return system_errors::system_EUSERS;
      case 88: return system_errors::system_ENOTSOCK;
      case 89: return system_errors::system_EDESTADDRREQ;
      case 90: return system_errors::system_EMSGSIZE;
      case 91: return system_errors::system_EPROTOTYPE;
      case 92: return system_errors::system_ENOPROTOOPT;
      case 93: return system_errors::system_EPROTONOSUPPORT;
      case 94: return system_errors::system_ESOCKTNOSUPPORT;
      case 95: return system_errors::system_EOPNOTSUPP;
      case 96: return system_errors::system_EPFNOSUPPORT;
      case 97: return system_errors::system_EAFNOSUPPORT;
      case 98: return system_errors::system_EADDRINUSE;
      case 99: return system_errors::system_EADDRNOTAVAIL;
      case 100: return system_errors::system_ENETDOWN;
      case 101: return system_errors::system_ENETUNREACH;
      case 102: return system_errors::system_ENETRESET;
      case 103: return system_errors::system_ECONNABORTED;
      case 104: return system_errors::system_ECONNRESET;
      case 105: return system_errors::system_ENOBUFS;
      case 106: return system_errors::system_EISCONN;
      case 107: return system_errors::system_ENOTCONN;
      case 108: return system_errors::system_ESHUTDOWN;
      case 109: return system_errors::system_ETOOMANYREFS;
      case 110: return system_errors::system_ETIMEDOUT;
      case 111: return system_errors::system_ECONNREFUSED;
      case 112: return system_errors::system_EHOSTDOWN;
      case 113: return system_errors::system_EHOSTUNREACH;
      case 114: return system_errors::system_EALREADY;
      case 115: return system_errors::system_EINPROGRESS;
      case 116: return system_errors::system_ESTALE;
      case 117: return system_errors::system_EUCLEAN;
      case 118: return system_errors::system_ENOTNAM;
      case 119: return system_errors::system_ENAVAIL;
      case 120: return system_errors::system_EISNAM;
      case 121: return system_errors::system_EREMOTEIO;
      case 122: return system_errors::system_EDQUOT;
      case 123: return system_errors::system_ENOMEDIUM;
      case 124: return system_errors::system_EMEDIUMTYPE;
      case 125: return system_errors::system_ECANCELED;
      case 126: return system_errors::system_ENOKEY;
      case 127: return system_errors::system_EKEYEXPIRED;
      case 128: return system_errors::system_EKEYREVOKED;
      case 129: return system_errors::system_EKEYREJECTED;
      case 130: return system_errors::system_EOWNERDEAD;
      case 131: return system_errors::system_ENOTRECOVERABLE;
      case 132: return system_errors::system_ERFKILL;
      case 133: return system_errors::system_EHWPOISON;
      default: return system_errors::system_UNKNOWN;
    }
}

} // namespace wf::utils
