$pdf_mode = 1;
$out_dir  = 'out';

$xelatex = 'xelatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$latex   = $xelatex;
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';

$pdf_previewer = 'start';
