#include <newdb/json_escape.h>
#include <newdb/runtime_stats_snapshot_json_write.h>
#include <newdb/txn_runtime_stats_snapshot.h>

#include <ostream>

namespace newdb {

void append_runtime_stats_snapshot_json_members_before_where(std::ostream& oss, const TxnRuntimeStats& stats) {
    oss << "\"vacuum_trigger_count\":" << stats.vacuum_trigger_count << ","
        << "\"vacuum_execute_count\":" << stats.vacuum_execute_count << ","
        << "\"vacuum_cooldown_skip_count\":" << stats.vacuum_cooldown_skip_count << ","
        << "\"vacuum_compact_success_count\":" << stats.vacuum_compact_success_count << ","
        << "\"vacuum_compact_failure_count\":" << stats.vacuum_compact_failure_count << ","
        << "\"vacuum_compact_bytes_reclaimed\":" << stats.vacuum_compact_bytes_reclaimed << ","
        << "\"vacuum_compact_last_elapsed_ms\":" << stats.vacuum_compact_last_elapsed_ms << ","
        << "\"vacuum_queue_depth\":" << stats.vacuum_queue_depth << ","
        << "\"vacuum_queue_depth_peak\":" << stats.vacuum_queue_depth_peak << ","
        << "\"maintenance_checkpoint_trigger_count\":" << stats.maintenance_checkpoint_trigger_count << ","
        << "\"maintenance_checkpoint_vacuum_enqueue_count\":" << stats.maintenance_checkpoint_vacuum_enqueue_count
        << ","
        << "\"write_conflicts\":" << stats.write_conflict_count << ","
        << "\"write_conflict_wait_count\":" << stats.write_conflict_wait_count << ","
        << "\"write_conflict_wait_timeout_count\":" << stats.write_conflict_wait_timeout_count << ","
        << "\"lock_wait_ms_total\":" << stats.lock_wait_ms_total << ","
        << "\"lock_wait_max_ms\":" << stats.lock_wait_max_ms << ","
        << "\"lock_deadlock_detect_count\":" << stats.lock_deadlock_detect_count << ","
        << "\"lock_deadlock_victim_count\":" << stats.lock_deadlock_victim_count << ","
        << "\"txn_begin_lock_conflicts\":" << stats.txn_begin_lock_conflict_count << ","
        << "\"wal_compact_count\":" << stats.wal_compact_count << ","
        << "\"wal_recovery_runs\":" << stats.wal_recovery_runs << ","
        << "\"wal_recovery_undo_ops\":" << stats.wal_recovery_undo_ops << ","
        << "\"wal_recovery_last_elapsed_ms\":" << stats.wal_recovery_last_elapsed_ms << ","
        << "\"wal_recovery_analyze_ms\":" << stats.wal_recovery_analyze_ms << ","
        << "\"wal_recovery_undo_ms\":" << stats.wal_recovery_undo_ms << ","
        << "\"wal_recovery_finalize_ms\":" << stats.wal_recovery_finalize_ms << ","
        << "\"wal_recovery_records_scanned\":" << stats.wal_recovery_records_scanned << ","
        << "\"wal_recovery_dangling_txns\":" << stats.wal_recovery_dangling_txns << ","
        << "\"wal_recovery_redo_ms\":" << stats.wal_recovery_redo_ms << ","
        << "\"wal_recovery_checkpoint_begin_count\":" << stats.wal_recovery_checkpoint_begin_count << ","
        << "\"wal_recovery_checkpoint_end_count\":" << stats.wal_recovery_checkpoint_end_count << ","
        << "\"wal_recovery_records_after_checkpoint\":" << stats.wal_recovery_records_after_checkpoint << ","
        << "\"wal_recovery_segments_after_checkpoint\":" << stats.wal_recovery_segments_after_checkpoint << ","
        << "\"wal_recovery_redo_plan_pending_txn_count\":" << stats.wal_recovery_redo_plan_pending_txn_count
        << ","
        << "\"wal_recovery_apply_conflict_count\":" << stats.wal_recovery_apply_conflict_count << ","
        << "\"wal_recovery_policy\":\"" << newdb::json_escape(stats.wal_recovery_policy) << "\","
        << "\"write_conflict_last_sample\":\"" << newdb::json_escape(stats.write_conflict_last_sample) << "\","
        << "\"file_lock_acquire_fail_count\":" << stats.file_lock_acquire_fail_count << ","
        << "\"file_lock_same_process_reuse_count\":" << stats.file_lock_same_process_reuse_count << ","
        << "\"file_lock_stale_marker_count\":" << stats.file_lock_stale_marker_count << ","
        << "\"sidecar_invalidate_count\":" << stats.sidecar_invalidate_count << ","
        << "\"sidecar_invalidate_fail_count\":" << stats.sidecar_invalidate_fail_count << ","
        << "\"wal_group_commit_count\":" << stats.wal_group_commit_count << ","
        << "\"wal_group_commit_batch_commits\":" << stats.wal_group_commit_batch_commits << ","
        << "\"wal_group_commit_pending_commits\":" << stats.wal_group_commit_pending_commits << ","
        << "\"txn_commit_count\":" << stats.txn_commit_count << ","
        << "\"txn_commit_p95_ms\":" << stats.txn_commit_p95_ms << ","
        << "\"txn_commit_max_ms\":" << stats.txn_commit_max_ms << ","
        << "\"wal_bytes_since_start\":" << stats.wal_bytes_since_start << ","
        << "\"wal_bytes_per_commit_avg\":" << stats.wal_bytes_per_commit_avg << ","
        << "\"lock_wait_p95_ms\":" << stats.lock_wait_p95_ms << ","
        << "\"scheduler_throttle_count\":" << stats.scheduler_throttle_count << ","
        << "\"hot_index_enabled\":" << (stats.hot_index_enabled ? "true" : "false") << ","
        << "\"segment_target_bytes\":" << stats.segment_target_bytes << ","
        << "\"lsm_memtable_flush_count\":" << stats.lsm_memtable_flush_count << ","
        << "\"lsm_compaction_count\":" << stats.lsm_compaction_count << ","
        << "\"lsm_segment_count\":" << stats.lsm_segment_count << ","
        << "\"lsm_memtable_bytes\":" << stats.lsm_memtable_bytes << ","
        << "\"lsm_read_segments_scanned\":" << stats.lsm_read_segments_scanned << ","
        << "\"lsm_read_segments_scanned_p95\":" << stats.lsm_read_segments_scanned_p95 << ","
        << "\"lsm_compaction_bytes_in\":" << stats.lsm_compaction_bytes_in << ","
        << "\"lsm_compaction_bytes_out\":" << stats.lsm_compaction_bytes_out << ","
        << "\"lsm_compaction_queue_pending\":" << stats.lsm_compaction_queue_pending << ","
        << "\"lsm_compaction_queue_inflight\":" << stats.lsm_compaction_queue_inflight << ","
        << "\"lsm_compaction_enqueue_skipped_backpressure\":"
        << stats.lsm_compaction_enqueue_skipped_backpressure << ","
        << "\"lsm_segment_cache_hits\":" << stats.lsm_segment_cache_hits << ","
        << "\"lsm_segment_cache_misses\":" << stats.lsm_segment_cache_misses << ","
        << "\"rollback_savepoint_count\":" << stats.rollback_savepoint_count << ","
        << "\"rollback_partial_ops\":" << stats.rollback_partial_ops << ","
        << "\"pitr_runs\":" << stats.pitr_runs << ","
        << "\"pitr_target_lsn\":" << stats.pitr_target_lsn << ","
        << "\"pitr_elapsed_ms\":" << stats.pitr_elapsed_ms << ","
        << "\"undo_chain_fallback_count\":" << stats.undo_chain_fallback_count << ","
        << "\"lazy_materialize_count\":" << stats.lazy_materialize_count << ","
        << "\"lazy_materialize_rows_total\":" << stats.lazy_materialize_rows_total << ","
        << "\"lazy_materialize_max_rows\":" << stats.lazy_materialize_max_rows << ","
        << "\"lazy_materialize_elapsed_ms\":" << stats.lazy_materialize_elapsed_ms << ",";
}

void append_runtime_stats_snapshot_json_members_after_heap(std::ostream& oss, const TxnRuntimeStats& stats) {
    oss << "\"vacuum_priority_score\":" << stats.vacuum_priority_score << ","
        << "\"vacuum_health_bonus_last\":" << stats.vacuum_health_bonus_last << ","
        << "\"vacuum_score_file_bytes_term\":" << stats.vacuum_score_file_bytes_term << ","
        << "\"vacuum_score_health_bonus_term\":" << stats.vacuum_score_health_bonus_term << ","
        << "\"vacuum_score_wal_since_term\":" << stats.vacuum_score_wal_since_term << ","
        << "\"compact_debt_bytes\":" << stats.compact_debt_bytes << ","
        << "\"compact_debt_rows\":" << stats.compact_debt_rows << ","
        << "\"compact_debt_ratio\":" << stats.compact_debt_ratio << ","
        << "\"compact_debt_priority\":" << stats.compact_debt_priority << ","
        << "\"page_cache_hits\":" << stats.page_cache_hits << ","
        << "\"page_cache_misses\":" << stats.page_cache_misses << ","
        << "\"page_cache_evictions\":" << stats.page_cache_evictions << ","
        << "\"page_cache_bytes_in_cache\":" << stats.page_cache_bytes_in_cache << ","
        << "\"memory_budget_max_bytes\":" << stats.memory_budget_max_bytes << ","
        << "\"memory_budget_used_bytes\":" << stats.memory_budget_used_bytes << ","
        << "\"memory_budget_reject_count\":" << stats.memory_budget_reject_count << ","
        << "\"memory_budget_bytes_evicted_total\":" << stats.memory_budget_bytes_evicted_total << ","
        << "\"memory_budget_sidecar_load_skipped_total\":" << stats.memory_budget_sidecar_load_skipped_total
        << ","
        << "\"mem_page_cache_used_bytes\":" << stats.mem_page_cache_used_bytes << ","
        << "\"mem_page_cache_evictions\":" << stats.mem_page_cache_evictions << ","
        << "\"mem_page_cache_admit_rejects\":" << stats.mem_page_cache_admit_rejects << ","
        << "\"mem_sidecar_used_bytes\":" << stats.mem_sidecar_used_bytes << ","
        << "\"mem_sidecar_evictions\":" << stats.mem_sidecar_evictions << ","
        << "\"mem_sidecar_admit_rejects\":" << stats.mem_sidecar_admit_rejects << ","
        << "\"mem_query_temp_used_bytes\":" << stats.mem_query_temp_used_bytes << ","
        << "\"mem_query_temp_evictions\":" << stats.mem_query_temp_evictions << ","
        << "\"mem_query_temp_admit_rejects\":" << stats.mem_query_temp_admit_rejects << ","
        << "\"mem_global_used_bytes\":" << stats.mem_global_used_bytes << ","
        << "\"mem_global_admit_rejects\":" << stats.mem_global_admit_rejects << ","
        << "\"txn_snapshot_refresh_count\":" << stats.txn_snapshot_refresh_count << ","
        << "\"txn_snapshot_pinned_count\":" << stats.txn_snapshot_pinned_count << ","
        << "\"txn_readpath_disabled_count\":" << stats.txn_readpath_disabled_count << ","
        << "\"last_snapshot_source\":\"" << newdb::json_escape(stats.last_snapshot_source) << "\","
        << "\"transaction_snapshot_lsn\":" << stats.transaction_snapshot_lsn << ","
        << "\"statement_snapshot_lsn\":" << stats.statement_snapshot_lsn << ","
        << "\"lock_key_range_count\":" << stats.lock_key_range_count << ","
        << "\"lock_key_predicate_count\":" << stats.lock_key_predicate_count << ","
        << "\"table_storage_health_logical_rows\":" << stats.table_storage_health_logical_rows << ","
        << "\"table_storage_health_physical_rows\":" << stats.table_storage_health_physical_rows << ","
        << "\"table_storage_health_tombstone_rows\":" << stats.table_storage_health_tombstone_rows << ","
        << "\"table_storage_health_data_file_bytes\":" << stats.table_storage_health_data_file_bytes << ","
        << "\"table_storage_health_live_bytes\":" << stats.table_storage_health_live_bytes << ","
        << "\"table_storage_health_dead_bytes\":" << stats.table_storage_health_dead_bytes << ","
        << "\"table_storage_health_fragmentation_ratio\":" << stats.table_storage_health_fragmentation_ratio
        << ","
        << "\"table_storage_health_last_vacuum_lsn\":" << stats.table_storage_health_last_vacuum_lsn << ","
        << "\"table_storage_health_last_vacuum_elapsed_ms\":" << stats.table_storage_health_last_vacuum_elapsed_ms
        << ","
        << "\"table_storage_health_tier\":\"" << newdb::json_escape(stats.table_storage_health_tier) << "\","
        << "\"write_heap_append_p95_ms\":" << stats.write_heap_append_p95_ms << ","
        << "\"write_heap_append_max_ms\":" << stats.write_heap_append_max_ms << ","
        << "\"write_hot_index_p95_ms\":" << stats.write_hot_index_p95_ms << ","
        << "\"write_hot_index_max_ms\":" << stats.write_hot_index_max_ms << ","
        << "\"write_sidecar_invalidate_p95_ms\":" << stats.write_sidecar_invalidate_p95_ms << ","
        << "\"write_sidecar_invalidate_max_ms\":" << stats.write_sidecar_invalidate_max_ms << ","
        << "\"write_wal_append_p95_ms\":" << stats.write_wal_append_p95_ms << ","
        << "\"write_wal_append_max_ms\":" << stats.write_wal_append_max_ms << ","
        << "\"write_lsm_track_p95_ms\":" << stats.write_lsm_track_p95_ms << ","
        << "\"write_lsm_track_max_ms\":" << stats.write_lsm_track_max_ms << ","
        << "\"write_lsm_flush_p95_ms\":" << stats.write_lsm_flush_p95_ms << ","
        << "\"write_lsm_flush_max_ms\":" << stats.write_lsm_flush_max_ms << ","
        << "\"write_lsm_compaction_p95_ms\":" << stats.write_lsm_compaction_p95_ms << ","
        << "\"write_lsm_compaction_max_ms\":" << stats.write_lsm_compaction_max_ms << ","
        << "\"write_lsm_rotate_compact_p95_ms\":" << stats.write_lsm_rotate_compact_p95_ms << ","
        << "\"write_lsm_rotate_compact_max_ms\":" << stats.write_lsm_rotate_compact_max_ms << ",";
}

} // namespace newdb
