#!
# @file Makefile
# @brief
# meta模块
#
# @author niexw
# @email niexiaowen@uestc.edu.cn
#
INCLUDE := $(SOURCE_DIR)

PROGRAMS := test_static_hash test_type_index test_quote test_tag_invoke

test_static_hash_SOURCES := test_static_hash.cc
test_type_index_SOURCES := test_type_index.cc
test_quote_SOURCES := test_quote.cc
test_tag_invoke_SOURCES := test_tag_invoke.cc

include $(SOURCE_DIR)/rules/program.mk
