name: newdb

on:
  push:
    paths:
      - "newdb/**"
      - "waterfall/**"
      - ".github/workflows/newdb-ci.yml"
      - "newdb/.github/workflows/**"
  pull_request:
    paths:
      - "newdb/**"
      - "waterfall/**"
      - ".github/workflows/newdb-ci.yml"
      - "newdb/.github/workflows/**"
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  reusable-ci:
    uses: ./newdb/.github/workflows/newdb-ci-reusable.yml
